
disabled_rules:
    - line_length
    - weak_delegate
    - cyclomatic_complexity
    - force_unwrapping
    - function_body_length
    - identifier_name
    - type_name
#
#included:
#    - Source
excluded:
    - Pods
    - paprikasTests
    - paprikasUITests
